spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fastlms
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: shgmlcks

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: shgmlcks1004@gmail.com
    password: **** **** **** ****
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            
logging:
  level:
    root: info
    
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

